spring.application.name=ilCavallinoSpringVersion

# SETTING DEL TIPO DI DATABASE UTILIZZATO
spring.jpa.database=POSTGRESQL
spring.datasource.platform=postgres

# URL DEL DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/ilcavallinodb



# CREDENZIALI DI ACCESSO AL DB
spring.datasource.username=francescomiriello
spring.datasource.password=""

# ATTIVA IL LOGGING DELLE QUERY GENERATE DA HIBERNATE E AUTORIZZA
# HIBERNATE AD ESEGUIRE COMANDI COME LA CREAZIONE DELLE TABELLE
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

application.security.jwt.secret-key=${JWT_SECRET}