spring.application.name=ilCavallinoSpringVersion
#URL DEL DATABASE
spring.datasource.url=

#CREDENZIALI DI ACCESSO AL DB
spring.datasource.username=
spring.datasource.password=

application.security.jwt.secret-key=${JWT_SECRET}