spring.application.name=ilCavallinoSpringVersion
#URL DEL DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/ilcavallinodb

#CREDENZIALI DI ACCESSO AL DB
spring.datasource.username=francescomiriello
spring.datasource.password=""
spring.jpa.hibernate.ddl-auto=update

application.security.jwt.secret-key=${JWT_SECRET}